name: serialize_enum

description: Json serialization for Dart enumerations without source code generation.

version: 0.1.1

repository: https://github.com/simphotonics/serialize_enum

topics:
  - enum
  - json
  - serialization
  - persist

environment:
  sdk: ^3.3.4

dependencies:
  exception_templates: ^0.3.1
  lazy_memo: ^0.2.3

dev_dependencies:
  benchmark_runner: ^0.1.7
  lints: ^4.0.0
  test: ^1.25.5
